---
# Le secret github-runner-token doit être créé AVANT avec kubectl:
# kubectl create secret generic github-runner-token --from-literal=token=VOTRE_TOKEN
# IMPORTANT: Le token GitHub expire après 1h !
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-token
              key: token
        - name: REPO_URL
          value: "https://github.com/BrahimHmitti/DEVOPS-jour4"
        - name: RUNNER_NAME
          value: "k8s-runner"
        - name: RUNNER_WORKDIR
          value: "/tmp/runner/work"
        - name: RUNNER_GROUP
          value: "default"
        - name: LABELS
          value: "self-hosted,kubernetes,linux"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket