apiVersion: v1
kind: Namespace
metadata:
  name: renovate
---
# Le secret renovate-github-token doit être créé AVANT avec kubectl:
# kubectl create secret generic renovate-github-token --from-literal=token=VOTRE_GITHUB_PAT -n renovate
# IMPORTANT: Ne jamais committer de secrets dans Git !
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |
    {
      "platform": "github",
      "autodiscover": false,
      "repositories": ["BrahimHmitti/DEVOPS-jour4"],
      "onboarding": false,
      "requireConfig": "optional",
      "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
      "kubernetes": {
        "fileMatch": ["(^|/).*\\.ya?ml$"]
      },
      "helm-values": {
        "fileMatch": ["(^|/)values\\.ya?ml$"]
      },
      "docker": {
        "enabled": true
      },
      "packageRules": [
        {
          "matchUpdateTypes": ["minor", "patch"],
          "automerge": true
        }
      ]
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: renovate
            image: renovate/renovate:latest
            env:
            - name: LOG_LEVEL
              value: "info"
            - name: RENOVATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: renovate-github-token
                  key: token
            - name: RENOVATE_CONFIG_FILE
              value: "/config/config.json"
            volumeMounts:
            - name: config
              mountPath: /config
          volumes:
          - name: config
            configMap:
              name: renovate-config
          restartPolicy: Never